accessing
exception: anObject
	exception := anObject